import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar/navbar';
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>The Contractor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
       <h1>The Contractor</h1>
       <p>Can he contract it? Yes he can.</p>
      </main>
    </>
  )
}
